### ISSUE TITLE
vagrant up: "The box 'debian/jessie64' could not be found"

### ISSUE THREAD

**Issue by tigrantv** [bupy7/zf-app-blank#1]
я не сильно разбираюсь в vagrant, но по readme не запускается.

жду помощи.
хочется запустить, пощупать.

```
vagrant up
Bringing machine 'zf-app-blank' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'debian/jessie64' could not be found.
* It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

**Comment by bupy7** [comment]
На Windows не ориентировалось. Настройки для unix-подобных систем. NFS в Windows не поддерживается.
С Windows не работаю. Можете попробовать заменить строку в `Vagrantfile`:

```
config.vm.synced_folder ".", "/vagrant", type: "nfs"
```

на

```
config.vm.synced_folder ".", "/vagrant", type: "smb"
```

И сейчас наврятли сборка будет полноценно работать. Автор debugbar'a выкатил последнюю версию с багами.

**Comment by bupy7** [comment]
Я форкнул DebugBar и исправил проблему. Если еще не запустили с Вагрантом - рекомендую ознакомится с его возможностями. Полезная вещь.
Либо разворачивайте своими силами и делайте проверку всех нужных пакетов через `php bin/requirements`. Но, отображение данного чекера под Windows так же не адаптировано. Возможно, будет что-то странное на выходе.
